package model.service;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import model.service.common.AppModule;


import model.view.HolidayCalendarSearchVOImpl;


import model.view.WpHolidayCalendarVOImpl;
import model.view.WpMonthListVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 12 15:58:55 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
        
      //  System.out.println("---------------- app module initialized --------------------------------------");
        
    }


    public void setSessionValues(String orgId, String userId, String respId,
                                 String respApplId) {
       
        
       orgId = "340";
        FacesContext fctx = FacesContext.getCurrentInstance();
        ExternalContext ectx = fctx.getExternalContext();
        HttpSession userSession = (HttpSession)ectx.getSession(false);

        if (orgId != null) {
            userSession.setAttribute("orgId", orgId);
        }

        if (userId != null) {
            userSession.setAttribute("userId", userId);
        }

        if (respId != null) {
            userSession.setAttribute("respId", respId);
        }

        if (respApplId != null) {
            userSession.setAttribute("respApplId", respApplId);
        }         
         
      }


    /**
     * Container's getter for HolidayCalendarSearchVO1.
     * @return HolidayCalendarSearchVO1
     */
    public HolidayCalendarSearchVOImpl getHolidayCalendarSearchVO1() {
        return (HolidayCalendarSearchVOImpl)findViewObject("HolidayCalendarSearchVO1");
    }

    /**
     * Container's getter for WpMonthListVO1.
     * @return WpMonthListVO1
     */
    public WpMonthListVOImpl getWpMonthListVO1() {
        return (WpMonthListVOImpl)findViewObject("WpMonthListVO1");
    }

    /**
     * Container's getter for HolidayCalendarSearchVO_vs_WpMonthListVO_vl1.
     * @return HolidayCalendarSearchVO_vs_WpMonthListVO_vl1
     */
    public ViewLinkImpl getHolidayCalendarSearchVO_vs_WpMonthListVO_vl1() {
        return (ViewLinkImpl)findViewLink("HolidayCalendarSearchVO_vs_WpMonthListVO_vl1");
    }

    /**
     * Container's getter for WpHolidayCalendarVO1.
     * @return WpHolidayCalendarVO1
     */
    public ViewObjectImpl getWpHolidayCalendarVO1() {
        return (ViewObjectImpl)findViewObject("WpHolidayCalendarVO1");
    }

    /**
     * Container's getter for WpHolidayCalendarR01Link1.
     * @return WpHolidayCalendarR01Link1
     */
    public ViewLinkImpl getWpHolidayCalendarR01Link1() {
        return (ViewLinkImpl)findViewLink("WpHolidayCalendarR01Link1");
    }

    /**
     * Container's getter for OrgVO1.
     * @return OrgVO1
     */
    public ViewObjectImpl getOrgVO1() {
        return (ViewObjectImpl)findViewObject("OrgVO1");
    }
}
