package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 17 12:37:02 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SpCalendarLVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SpCalendarLVOImpl() {
    }
}
