package model.view;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 15 17:36:34 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SpCalendarHVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SpCalendarHVOImpl() {
    }



}
